//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasUSAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CICLO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CICLO()
        {
            this.CICLO_CARRERA = new HashSet<CICLO_CARRERA>();
        }
    
        public int ID_CICLO { get; set; }
        public string COD_CICLO { get; set; }
        public int DOCENTE { get; set; }
        public int MATERIA { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
    
        public virtual DOCENTE DOCENTE1 { get; set; }
        public virtual MATERIAS MATERIAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CICLO_CARRERA> CICLO_CARRERA { get; set; }
    }
}
