//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasUSAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CICLO_CARRERA
    {
        public int ID_CICLO_CARRERA { get; set; }
        public int ID_CICLO { get; set; }
        public int ID_CARRERA { get; set; }
    
        public virtual CARRERA CARRERA { get; set; }
        public virtual CICLO CICLO { get; set; }
    }
}
