//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasUSAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COORDINADOR
    {
        public int ID_COORDINADOR { get; set; }
        public System.DateTime FECHA_INGRESO { get; set; }
        public int PERSONA { get; set; }
        public int FACULTAD { get; set; }
        public int PROFESION { get; set; }
    
        public virtual FACULTAD FACULTAD1 { get; set; }
        public virtual PERSONA PERSONA1 { get; set; }
        public virtual PROFESION PROFESION1 { get; set; }
    }
}
