//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasUSAM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ENCUESTASUSAMEntities : DbContext
    {
        public ENCUESTASUSAMEntities()
            : base("name=ENCUESTASUSAMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALUMNOS> ALUMNOS { get; set; }
        public virtual DbSet<CARRERA> CARRERA { get; set; }
        public virtual DbSet<CICLO> CICLO { get; set; }
        public virtual DbSet<CICLO_CARRERA> CICLO_CARRERA { get; set; }
        public virtual DbSet<COORDINADOR> COORDINADOR { get; set; }
        public virtual DbSet<DEPARTAMENTO> DEPARTAMENTO { get; set; }
        public virtual DbSet<DISENIO_INVESTIGACION> DISENIO_INVESTIGACION { get; set; }
        public virtual DbSet<DOCENTE> DOCENTE { get; set; }
        public virtual DbSet<FACULTAD> FACULTAD { get; set; }
        public virtual DbSet<GRUPO_ALUMNO> GRUPO_ALUMNO { get; set; }
        public virtual DbSet<MATERIA_ALUMNO> MATERIA_ALUMNO { get; set; }
        public virtual DbSet<MATERIAS> MATERIAS { get; set; }
        public virtual DbSet<PERSONA> PERSONA { get; set; }
        public virtual DbSet<PROFESION> PROFESION { get; set; }
        public virtual DbSet<PROYECTO> PROYECTO { get; set; }
        public virtual DbSet<ROL_USUARIO> ROL_USUARIO { get; set; }
        public virtual DbSet<SEXO> SEXO { get; set; }
        public virtual DbSet<TIPO_INVESTIGACION> TIPO_INVESTIGACION { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
