//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasUSAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROYECTO
    {
        public int ID { get; set; }
        public string NOMBRE_PROYECTO { get; set; }
        public string DESCRIPCION { get; set; }
        public int ID_TIPO_INVESTIGACION { get; set; }
        public int ID_MATERIA { get; set; }
        public int ID_DISENIO_INVESTIGACION { get; set; }
        public Nullable<System.DateTime> FECHA_ASIGNACION { get; set; }
        public int ID_GRUPO_ALUMNO { get; set; }
    
        public virtual DISENIO_INVESTIGACION DISENIO_INVESTIGACION { get; set; }
        public virtual GRUPO_ALUMNO GRUPO_ALUMNO { get; set; }
        public virtual MATERIAS MATERIAS { get; set; }
        public virtual TIPO_INVESTIGACION TIPO_INVESTIGACION { get; set; }
    }
}
