//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EncuestasUSAM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int ID_USUARIO { get; set; }
        public string NOMBRE_USUARIO { get; set; }
        public byte[] PASSWORD { get; set; }
        public Nullable<bool> ESTADO_PERMISO { get; set; }
        public Nullable<int> ID_TIPO_USUARIO { get; set; }
        public Nullable<int> ID_PERSONA_USUARIO { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        public virtual ROL_USUARIO ROL_USUARIO { get; set; }
    }
}
